### ISSUE TITLE
Why include kubernetes ?

### ISSUE THREAD

**Issue by izzatzr** [chris-chris/ml-engineer-roadmap#3]
I think ml engineer dont really need to know how to operate kubernetes

**Comment by steven-mi** [comment]
Kubernetes helps you managing your resources and can make your application scaleable. Hence it would be good to know Kubernetes. Note that ML Engineer not only do ML.

**Comment by JuHyung-Son** [comment]
I agree with @steven-mi since most of ml system, pipeline runs on cloud environment, k8s is important to ml engineer.
